// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'long': string;
  'method-item': string;
  'methodItem': string;
  'short': string;
}
export const cssExports: CssExports;
export default cssExports;
